services:
  db:
    container_name: oniocdn-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: niooi
      POSTGRES_PASSWORD: abcde
      POSTGRES_DB: postgres
    ports:
      - 9432:5432
    volumes:
      - oniocdn-data:/var/lib/postgresql/data

volumes:
  oniocdn-data: 
