services:
  db:
    container_name: ocloud-cdn-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: niooi
      POSTGRES_PASSWORD: abcde
      POSTGRES_DB: postgres
    ports:
      - 9432:5432
    volumes:
      - ocloud-cdn-data:/var/lib/postgresql/data

volumes:
  ocloud-cdn-data: 
